version: '3.8'

services:
  backend:
    container_name: dictary-backend
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./src/config/environments/common.env
      - ./src/config/environments/local.env
      - ./src/config/environments/docker.env
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - dictary-network
  mongodb:
    container_name: dictary-mongo
    image: mongo:latest
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate() }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      retries: 30
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/.data/db
    networks:
      - dictary-network

volumes:
  mongo_data: {}

networks:
  dictary-network:
    driver: bridge