name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - development
  workflow_call:

jobs:
  tests:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.x
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Prettier check
        run: npm run prettier:check

      - name: Start MongoDB
        run: docker-compose -f "docker-compose.testing.yml" up -d --build

      - name: Tests api
        run: npm run test:api

      - name: Tests e2e
        run: npm run test:e2e

      - name: Tests security
        run: npm run test:security